// <auto-generated />
namespace ERecruitment.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hello : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hello));
        
        string IMigrationMetadata.Id
        {
            get { return "201511030455022_hello"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
